// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtavbbqeiprtrgqwqtlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0YXZiYnFlaXBydHJncXdxdGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTAwNzMsImV4cCI6MjA3NTY2NjA3M30.4L6cTKCxHdvojkkGXKrULkbVjVG5UP7mVXfYjcXzw6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});